name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set PYTHONPATH environment variable
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE/testselenium/configfile/config.py" >> $GITHUB_ENV

    # Step 5: Set other environment variables
    - name: Set Environment Variables
      run: |
        echo "PYTHONPATH=$PWD/testselenium/configfile/config.py" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://127.0.0.1:27017/sampleupload" >> $GITHUB_ENV

    # Step 6: Wait for MongoDB to be ready
    - name: Wait for MongoDB to be ready
      run: |
        until nc -zv localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is ready"

    # Step 7: Configure MongoDB Test Data
    - name: Configure MongoDB Test Data
      run: |
        python configfile/config.py  # Adjust this path to your MongoDB setup script

    # Step 8: Set up ChromeDriver and Chrome
    - name: Set up ChromeDriver and Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    # Step 9: Set Timezone to India Standard Time (IST)
    - name: Set Timezone to IST
      run: sudo timedatectl set-timezone Asia/Kolkata  

    # Step 10: List files and directories 
    - name: List all files and directories
      run: |
        ls -R  # Recursively lists all files and directories for debugging

    # Step 11: Run Selenium tests and generate HTML report
    - name: Run Selenium tests and generate HTML report
      id: run_tests
      run: |
        pytest --html=report.html --self-contained-html > pytest_test_results.log || exit 0
        cat pytest_test_results.log

    # Step 12: Archive Pytest Results
    - name: Archive Pytest Results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest_test_results.log

    # Step 13: Archive HTML Test Report
    - name: Archive HTML Test Report
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-report
        path: report.html
