name: CI with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongo --eval 'db.adminCommand({ ping: 1 })'" 
          --health-timeout 30s 
          --health-retries 3

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your dependencies, including Selenium

      # Step 4: Set Timezone to India Standard Time (IST)
      - name: Set Timezone to IST
        run: sudo timedatectl set-timezone Asia/Kolkata  

      # Step 5: List files and directories for debugging
      - name: List all files and directories
        run: |
          ls -R  # Recursively lists all files and directories for debugging

      # Step 6: Run Selenium tests and generate HTML report
      - name: Run Selenium tests and generate HTML report
        id: run_tests
        run: |
          pytest --html=report.html --self-contained-html > pytest_test_results.log || exit 0
          cat pytest_test_results.log

      # Step 7: Archive Pytest Results
      - name: Archive Pytest Results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: pytest_test_results.log

      # Step 8: Archive HTML Test Report
      - name: Archive HTML Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-report
          path: report.html
